[SERVICE] Fix ther sigterm handler function error caused by not enought input args
```
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/unmanic/service.py", line 308, in main
    service.run()
  File "/usr/local/lib/python3.8/dist-packages/unmanic/service.py", line 258, in run
    signal.pause()
TypeError: sig_handle() takes 2 positional arguments but 3 were given

```