[LIBRARIES PLUGINS] Fix bug causing error when saving a library containing a plugin with no config options
Since moving to multi library capibility, plugin settings will be saved when the library configuration is closed. This is not checking to see if a plugin actually has the ability to be configured before attempting to save an empty configuration which in turn then raises an exception.

This was not a breaking issue as Unmanic would catch that exception and log it. However, this adds a check to ensure a plugin has configuration options before attempting to save them.

Error:
```
2022-03-17T20:16:27:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception while saving settings for plugin 'extract_srt_subtitles_to_files' - module 'extract_srt_subtitles_to_files.plugin' has no attribute 'Settings'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 390, in save_plugin_settings
    plugin_settings = plugin_module.Settings(library_id=library_id)
AttributeError: module 'extract_srt_subtitles_to_files.plugin' has no attribute 'Settings'
2022-03-17T20:16:27:ERROR:Unmanic.PluginExecutor - [FORMATTED] - module 'extract_srt_subtitles_to_files.plugin' has no attribute 'Settings'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 390, in save_plugin_settings
    plugin_settings = plugin_module.Settings(library_id=library_id)
AttributeError: module 'extract_srt_subtitles_to_files.plugin' has no attribute 'Settings'
```