[FOREMAN LINKING FILEMONITOR LIBRARYSCANNER] Fix issue where fetching a library by an id that does not exist any more can throw an exception that is unrecoverable
```
Exception in thread Foreman:
Traceback (most recent call last):
  File "/home/josh5/dev/mystuff/unmanic/unmanic/libs/foreman.py", line 640, in run
    if not self.validate_worker_config():
  File "/home/josh5/dev/mystuff/unmanic/unmanic/libs/foreman.py", line 156, in validate_worker_config
    if self.configuration_changed():
  File "/home/josh5/dev/mystuff/unmanic/unmanic/libs/foreman.py", line 131, in configuration_changed
    current_settings = self.get_current_library_configuration()
  File "/home/josh5/dev/mystuff/unmanic/unmanic/libs/foreman.py", line 111, in get_current_library_configuration
    library_config = Library(library.get('id'))
  File "/home/josh5/dev/mystuff/unmanic/unmanic/libs/library.py", line 82, in __init__
    raise Exception("Unable to fetch library with ID {}".format(library_id))
Exception: Unable to fetch library with ID 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/josh5/dev/mystuff/unmanic/unmanic/libs/foreman.py", line 736, in run
    raise Exception(e)
Exception: Unable to fetch library with ID 3
```